source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

use_frameworks! :linkage => :static

platform :ios, '10.0'

target 'DoubleLink_Example' do
  pod 'DoubleLink', :path => '../'

  target 'DoubleLink_Tests' do
    inherit! :search_paths

    
  end
end
